### ISSUE TITLE
Need Sorting Algorithms [JAVA]

### ISSUE THREAD

**Issue by prkhrv** [prkhrv/Python-sorting#1]
Just Create a Folder For java Algorithms.

**Comment by aayushbisen** [comment]
Ok adding Java algorithms.

**Comment by the-vis-sharma** [comment]
I'm adding heap sort algorithm.

**Comment by son-vyas** [comment]
I will add Merge sort algorithm

**Comment by Joseph-Acevedo** [comment]
I can add JAVA mergesort and insertion sort

**Comment by prkhrv** [comment]
Hey @Joseph-Acevedo, Thanks for your interest but insertion sort is already added by @viyer014, you can go ahead with the MergeSort.

**Comment by son-vyas** [comment]
Hey @prkhrv, I am working on Merge sort.

**Comment by na-coding** [comment]
Adding BucketSort

**Comment by msyrgiy** [comment]
I can add BubbleSort

**Comment by msyrgiy** [comment]
Gnome sort is from me

**Comment by akashthakrar** [comment]
@prkhrv added patience sort
